// Mock data for preview when backend is unavailable
export const mockOverview = {
  days: 7,
  interval: 'day',
  sentiment_over_time: [
    { bucket: '2026-08-10', pos: 42, neg: 18, neutral: 40, avg_score: 0.24 },
    { bucket: '2026-08-11', pos: 38, neg: 22, neutral: 40, avg_score: 0.16 },
    { bucket: '2026-08-12', pos: 51, neg: 14, neutral: 35, avg_score: 0.37 },
    { bucket: '2026-08-13', pos: 33, neg: 31, neutral: 36, avg_score: 0.02 },
    { bucket: '2026-08-14', pos: 45, neg: 19, neutral: 36, avg_score: 0.26 },
    { bucket: '2026-08-15', pos: 56, neg: 12, neutral: 32, avg_score: 0.44 },
    { bucket: '2026-08-16', pos: 48, neg: 21, neutral: 31, avg_score: 0.27 },
  ],
  language_mix: [
    { bucket: '2026-08-10', mk: 55, sq: 18, en: 20, tr: 7 },
    { bucket: '2026-08-11', mk: 52, sq: 21, en: 19, tr: 8 },
    { bucket: '2026-08-12', mk: 60, sq: 16, en: 17, tr: 7 },
    { bucket: '2026-08-13', mk: 48, sq: 24, en: 21, tr: 7 },
    { bucket: '2026-08-14', mk: 53, sq: 20, en: 20, tr: 7 },
    { bucket: '2026-08-15', mk: 57, sq: 17, en: 19, tr: 7 },
    { bucket: '2026-08-16', mk: 54, sq: 19, en: 20, tr: 7 },
  ],
  trending_entities: [
    { text: 'Zoran Zaev', label: 'PER', mentions: 84 },
    { text: 'Skopje', label: 'LOC', mentions: 71 },
    { text: 'SDSM', label: 'ORG', mentions: 63 },
    { text: 'EU', label: 'ORG', mentions: 58 },
    { text: 'Hristijan Mickoski', label: 'PER', mentions: 47 },
    { text: 'VMRO-DPMNE', label: 'ORG', mentions: 44 },
    { text: 'Ohrid', label: 'LOC', mentions: 38 },
    { text: 'DUI', label: 'ORG', mentions: 35 },
    { text: 'Ali Ahmeti', label: 'PER', mentions: 29 },
    { text: 'Tetovo', label: 'LOC', mentions: 24 },
  ],
}

export const mockKpis = {
  total_articles: 4821,
  analyzed: 4619,
  entities: 1247,
  stories: 186,
  sentiment_pos: 44,
  sentiment_neg: 21,
  sentiment_neutral: 35,
}

export const mockSearchResults = {
  total: 312,
  results: [
    {
      id: '1',
      title: 'Македонија го интензивира дијалогот со ЕУ за членство',
      url: '#',
      source_name: 'MKD.mk',
      published_date: '2026-08-16T08:12:00Z',
      summary: 'Владата на Македонија одржа средба со претставници на ЕУ...',
      sentiment_label: 'positive',
      language: 'mk',
      rank: 0.94,
      entities: [{ text: 'EU', label: 'ORG' }, { text: 'Skopje', label: 'LOC' }],
    },
    {
      id: '2',
      title: 'Shqipëria dhe Maqedonia forcojnë marrëdhëniet dypalëshe',
      url: '#',
      source_name: 'Telma',
      published_date: '2026-08-15T14:30:00Z',
      summary: 'Ministrat e dy vendeve diskutuan marrëdhëniet ekonomike...',
      sentiment_label: 'positive',
      language: 'sq',
      rank: 0.87,
      entities: [{ text: 'Albania', label: 'LOC' }, { text: 'Ali Ahmeti', label: 'PER' }],
    },
    {
      id: '3',
      title: 'Opposition party VMRO-DPMNE rallies ahead of local elections',
      url: '#',
      source_name: 'Macedonia Herald',
      published_date: '2026-08-15T09:00:00Z',
      summary: 'VMRO-DPMNE organized a large rally in Skopje attracting thousands...',
      sentiment_label: 'neutral',
      language: 'en',
      rank: 0.81,
      entities: [{ text: 'VMRO-DPMNE', label: 'ORG' }, { text: 'Hristijan Mickoski', label: 'PER' }],
    },
    {
      id: '4',
      title: 'Ekonomik kriz Makedonya\'nın kuzey bölgelerini etkiliyor',
      url: '#',
      source_name: 'Koha',
      published_date: '2026-08-14T17:45:00Z',
      summary: 'Ekonomik göstergeler kuzey bölgelerinde işsizliğin arttığını...',
      sentiment_label: 'negative',
      language: 'tr',
      rank: 0.78,
      entities: [{ text: 'Tetovo', label: 'LOC' }, { text: 'SDSM', label: 'ORG' }],
    },
  ],
}

export const mockSentimentDist = {
  distribution: [
    { label: 'positive', count: 2031, avg_score: 0.61 },
    { label: 'neutral', count: 1617, avg_score: 0.02 },
    { label: 'negative', count: 971, avg_score: -0.54 },
  ],
  by_language: {
    mk: { positive: 1120, neutral: 890, negative: 510 },
    sq: { positive: 440, neutral: 380, negative: 240 },
    en: { positive: 360, neutral: 290, negative: 160 },
    tr: { positive: 111, neutral: 57, negative: 61 },
  },
  total_analyzed: 4619,
}

export const mockEntities = {
  total: 1247,
  nodes: [
    { id: 'e1', text: 'Zoran Zaev', label: 'PER', mention_count: 84, aliases: ['Z. Zaev'] },
    { id: 'e2', text: 'Skopje', label: 'LOC', mention_count: 71, aliases: ['Скопје'] },
    { id: 'e3', text: 'SDSM', label: 'ORG', mention_count: 63, aliases: [] },
    { id: 'e4', text: 'EU', label: 'ORG', mention_count: 58, aliases: ['European Union'] },
    { id: 'e5', text: 'Hristijan Mickoski', label: 'PER', mention_count: 47, aliases: [] },
    { id: 'e6', text: 'VMRO-DPMNE', label: 'ORG', mention_count: 44, aliases: [] },
    { id: 'e7', text: 'Ohrid', label: 'LOC', mention_count: 38, aliases: ['Охрид'] },
    { id: 'e8', text: 'DUI', label: 'ORG', mention_count: 35, aliases: ['BDI'] },
    { id: 'e9', text: 'Ali Ahmeti', label: 'PER', mention_count: 29, aliases: [] },
    { id: 'e10', text: 'Tetovo', label: 'LOC', mention_count: 24, aliases: ['Тетово'] },
    { id: 'e11', text: 'Bujar Osmani', label: 'PER', mention_count: 21, aliases: [] },
    { id: 'e12', text: 'NATO', label: 'ORG', mention_count: 19, aliases: [] },
  ],
}

export const mockGraphEdges = {
  edges: [
    { source: 'e1', target: 'e3', weight: 28, source_text: 'Zoran Zaev', source_label: 'PER', target_text: 'SDSM', target_label: 'ORG' },
    { source: 'e5', target: 'e6', weight: 24, source_text: 'Hristijan Mickoski', source_label: 'PER', target_text: 'VMRO-DPMNE', target_label: 'ORG' },
    { source: 'e9', target: 'e8', weight: 20, source_text: 'Ali Ahmeti', source_label: 'PER', target_text: 'DUI', target_label: 'ORG' },
    { source: 'e1', target: 'e2', weight: 18, source_text: 'Zoran Zaev', source_label: 'PER', target_text: 'Skopje', target_label: 'LOC' },
    { source: 'e3', target: 'e4', weight: 15, source_text: 'SDSM', source_label: 'ORG', target_text: 'EU', target_label: 'ORG' },
    { source: 'e6', target: 'e2', weight: 14, source_text: 'VMRO-DPMNE', source_label: 'ORG', target_text: 'Skopje', target_label: 'LOC' },
    { source: 'e11', target: 'e8', weight: 12, source_text: 'Bujar Osmani', source_label: 'PER', target_text: 'DUI', target_label: 'ORG' },
    { source: 'e4', target: 'e12', weight: 10, source_text: 'EU', source_label: 'ORG', target_text: 'NATO', target_label: 'ORG' },
    { source: 'e2', target: 'e7', weight: 9, source_text: 'Skopje', source_label: 'LOC', target_text: 'Ohrid', target_label: 'LOC' },
    { source: 'e5', target: 'e2', weight: 8, source_text: 'Hristijan Mickoski', source_label: 'PER', target_text: 'Skopje', target_label: 'LOC' },
  ],
}

export const mockStories = {
  total: 186,
  stories: [
    {
      id: 's1',
      title: 'EU Accession Negotiations Resume After Months of Stalling',
      language: 'en',
      dominant_sentiment: 'positive',
      avg_sentiment_score: 0.48,
      member_count: 23,
      top_entities: [{ id: 'e4', text: 'EU', label: 'ORG' }, { id: 'e3', text: 'SDSM', label: 'ORG' }],
      first_seen: '2026-08-10T06:00:00Z',
      last_seen: '2026-08-16T12:00:00Z',
      summary: 'Diplomatic talks between Skopje and Brussels resumed following a six-month standstill...',
    },
    {
      id: 's2',
      title: 'Pre-Election Tensions Rise in Northern Municipalities',
      language: 'mk',
      dominant_sentiment: 'negative',
      avg_sentiment_score: -0.31,
      member_count: 17,
      top_entities: [{ id: 'e6', text: 'VMRO-DPMNE', label: 'ORG' }, { id: 'e10', text: 'Tetovo', label: 'LOC' }],
      first_seen: '2026-08-12T00:00:00Z',
      last_seen: '2026-08-16T08:00:00Z',
      summary: 'Political tensions have escalated in Tetovo and surrounding municipalities ahead of local elections...',
    },
    {
      id: 's3',
      title: 'Ohrid Tourism Season Records Visitor High',
      language: 'mk',
      dominant_sentiment: 'positive',
      avg_sentiment_score: 0.72,
      member_count: 11,
      top_entities: [{ id: 'e7', text: 'Ohrid', label: 'LOC' }],
      first_seen: '2026-08-13T00:00:00Z',
      last_seen: '2026-08-15T18:00:00Z',
      summary: 'Ohrid Lake recorded its highest visitor count in five years during the current summer season...',
    },
    {
      id: 's4',
      title: 'Cross-Border Economic Cooperation Initiative Launched',
      language: 'sq',
      dominant_sentiment: 'neutral',
      avg_sentiment_score: 0.08,
      member_count: 9,
      top_entities: [{ id: 'e11', text: 'Bujar Osmani', label: 'PER' }, { id: 'e4', text: 'EU', label: 'ORG' }],
      first_seen: '2026-08-14T00:00:00Z',
      last_seen: '2026-08-16T10:00:00Z',
      summary: 'A new regional economic initiative aims to boost cross-border trade between Macedonia and Albania...',
    },
  ],
}
